Compile dvbloopback into Luis Alves' TBS drivers repo

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -64,8 +64,9 @@ show_help(){
   echo "                        want to compile. Like --vanilla=3.18.12"
   echo "                        This disables --stock option"
   echo "                        "
-  echo " --v4l=<opt>            [no] yes: compile current v4l tree"
+  echo " --v4l=<opt>            [no] yes: compile official current v4l tree"
   echo "                        against your running kernel"
+  echo "                        tbs: compile Luis Alves' v4l repo"
   echo "                        Disables --stock= and --vanilla="
   echo "                        "
   echo " --adapters=<opt>       [16] Set max number of adapters that are allowed,"
@@ -367,6 +368,9 @@ fi
 if [ "x$v4l_opt" = "xyes" ];then
   git clone git://linuxtv.org/media_build.git || die "Error(s) while fetching v4l build system"
   git clone --depth=1 git://linuxtv.org/media_tree.git || die "Error(s) while fetching v4l source tree"
+elif [ "x$v4l_opt" = "xtbs" ];then
+  git clone  git://github.com/ljalves/media_build.git || die "Error(s) while fetching v4l build system"
+  git clone --depth=1 git://github.com/ljalves/linux_media.git -b latest ./media_tree || die "Error(s) while fetching v4l source tree"
 fi
 
 # Vanilla
@@ -418,7 +422,7 @@ if [ "x$v4l_opt" = "xno" ]; then
 fi
 
 # v4l
-if [ "x$v4l_opt" = "xyes" ]; then
+if [ "x$v4l_opt" = "xyes" -o "x$v4l_opt" = "xtbs" ]; then
   cd media_tree
   mkdir drivers/media/pci/dvbloopback
   cp -f ../dvbloopback/* drivers/media/pci/dvbloopback/
@@ -597,7 +601,7 @@ Not going to install any more of those, aborting...
 fi
 
 # v4l
-if [ "x$v4l_opt" = "xyes" ]; then
+if [ "x$v4l_opt" = "xyes" -o "x$v4l_opt" = "xtbs" ]; then
   make distclean
   make allyesconfig
   sed -i "s/CONFIG_DVB_MAX_ADAPTERS=8/CONFIG_DVB_MAX_ADAPTERS=$adapters_opt/" v4l/.config
@@ -657,7 +661,7 @@ Aborting...
 fi
 
 # v4l
-if [ "x$v4l_opt" = "xyes" ]; then
+if [ "x$v4l_opt" = "xyes" -o "x$v4l_opt" = "xtbs" ]; then
   make
   if ! [ "$?" -eq "0" ]; then
     echo "
@@ -753,7 +757,7 @@ All done, you should reboot NOW!
 fi
 
 # v4l
-if [ "x$v4l_opt" = "xyes" ]; then
+if [ "x$v4l_opt" = "xyes" -o "x$v4l_opt" = "xtbs" ]; then
   if [ -d /lib/modules/`uname -r`/updates/media ]; then
     rm -rf /lib/modules/`uname -r`/updates/media
     depmod -a
